import { Metadata } from 'next';

export const metadata: Metadata = {
  title: "VOLTRIS - Suporte Técnico Remoto e Criação de Sites Profissionais",
  description: "Suporte técnico remoto especializado em Windows, criação de sites profissionais, otimização de computadores e manutenção de sistemas. Atendimento em todo Brasil, 100% online e seguro.",
  keywords: [
    "suporte técnico remoto",
    "manutenção de computador",
    "criação de sites",
    "otimização de Windows",
    "formatação de computador",
    "remoção de vírus",
    "instalação de programas",
    "suporte Windows",
    "manutenção remota",
    "tecnologia",
    "informática",
    "desenvolvimento web",
    "design de sites",
    "SEO",
    "marketing digital",
    "técnico de informática",
    "técnico informática",
    "criar site",
    "criadores de site",
    "técnico informática casa",
    "técnico informática região",
    "técnico informática minha região",
    "técnico informática atende casa",
    "técnico computador",
    "assistência técnica informática",
    "manutenção sistema",
    "reparo computador",
    "configuração computador",
    "instalação Windows",
    "backup dados",
    "recuperação dados",
    "instalação impressora",
    "configuração rede",
    "otimização PC",
    "correção erros Windows",
    "suporte técnico online",
    "formatação Windows",
    "instalação programas remota",
    "remoção malware",
    "otimização sistema",
    "antivírus",
    "firewall",
    "limpeza computador",
    "aceleração PC",
    "correção tela azul",
    "erro sistema",
    "problemas internet",
    "configuração email",
    "instalação software",
    "manutenção preventiva",
    "diagnóstico computador",
    "reparo remoto",
    "suporte 24h",
    "serviços informática",
    "soluções tecnológicas",
    "consultoria TI",
    "manutenção notebook",
    "formatação notebook",
    "otimização notebook",
    "configuração sistema",
    "migração dados",
    "virtualização",
    "cloud computing",
    "backup cloud",
    "segurança digital",
    "proteção dados",
    "criptografia",
    "VPN",
    "rede doméstica",
    "WiFi",
    "bluetooth",
    "periféricos",
    "mouse",
    "teclado",
    "webcam",
    "microfone",
    "alto-falantes",
    "headset",
    "gamepad",
    "joystick",
    "controle Xbox",
    "controle PlayStation",
    "steering wheel",
    "flight stick",
    "VR headset",
    "AR glasses",
    "smartphone",
    "tablet",
    "smartwatch",
    "smart TV",
    "Chromecast",
    "Fire Stick",
    "Apple TV",
    "Roku",
    "consoles",
    "Xbox",
    "PlayStation",
    "Nintendo",
    "PC gaming",
    "gaming laptop",
    "gaming desktop",
    "overclock",
    "water cooling",
    "air cooling",
    "thermal paste",
    "GPU",
    "CPU",
    "RAM",
    "SSD",
    "HDD",
    "NVMe",
    "motherboard",
    "power supply",
    "case",
    "fans",
    "RGB",
    "LED",
    "streaming",
    "OBS",
    "Streamlabs",
    "Twitch",
    "YouTube Gaming",
    "Facebook Gaming",
    "Discord",
    "TeamSpeak",
    "Mumble",
    "Steam",
    "Epic Games",
    "Origin",
    "Uplay",
    "Battle.net",
    "GOG",
    "itch.io",
    "Humble Bundle",
    "Green Man Gaming",
    "Fanatical",
    "G2A",
    "Kinguin",
    "CDKeys",
    "Nuuvem",
    "GamersGate",
    "IndieGala",
    "Bundle Stars",
    "Mac Games Store",
    "App Store",
    "Google Play",
    "Microsoft Store",
    "Sony PlayStation Store",
    "Nintendo eShop",
    "Xbox Store",
    "Amazon Games",
    "GameStop",
    "Best Buy",
    "Walmart",
    "Target",
    "Carrefour",
    "Extra",
    "Casas Bahia",
    "Magazine Luiza",
    "Americanas",
    "Submarino",
    "Netshoes",
    "Kabum",
    "Terabyte",
    "Pichau",
    "Amazon Brasil",
    "Mercado Livre",
    "OLX",
    "Enjoei",
    "B2W Digital",
    "Via Varejo",
    "Lojas Americanas",
    "Ricardo Eletro",
    "Fast Shop",
    "Saraiva",
    "Livraria Cultura",
    "Fnac",
    "Kalunga",
    "Staples",
    "Office Depot",
    "Staples Brasil",
    "Kalunga",
    "Saraiva",
    "Livraria Cultura",
    "Fnac"
  ],
  openGraph: {
    title: "VOLTRIS - Suporte Técnico Remoto e Criação de Sites Profissionais",
    description: "Suporte técnico remoto especializado em Windows, criação de sites profissionais, otimização de computadores e manutenção de sistemas. Atendimento em todo Brasil, 100% online e seguro.",
    url: "https://voltris.com.br",
    type: "website",
    images: [
      {
        url: "/remotebanner.jpg",
        width: 1200,
        height: 630,
        alt: "VOLTRIS - Suporte Técnico Remoto e Criação de Sites"
      }
    ]
  },
  twitter: {
    card: "summary_large_image",
    title: "VOLTRIS - Suporte Técnico Remoto e Criação de Sites Profissionais",
    description: "Suporte técnico remoto especializado em Windows, criação de sites profissionais, otimização de computadores e manutenção de sistemas.",
    images: ["/remotebanner.jpg"]
  },
  alternates: {
    canonical: "https://voltris.com.br"
  }
}; 