import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: '[2025] VOLTRIS OPTIMIZER - Otimizador de PC Profissional | Aumente FPS, Desempenho e Produtividade',
  description: 'VOLTRIS OPTIMIZER: Software brasileiro de otimização de PC. Aumente até 25% de FPS, elimine stutter e lag, otimização automática para 100+ jogos, redução de input lag em até 40%. Solução SaaS com controle remoto para gamers, empresas e uso doméstico. Setup instantâneo, tecnologia nacional inovadora.',
  keywords: [
    'otimizador de games',
    'aumentar fps em jogos',
    'eliminar lag em games',
    'otimização de pc para jogos',
    'melhorar performance em games',
    'reduzir stutter em jogos',
    'otimizador de sistema para gaming',
    'aumentar fps no pc',
    'eliminar input lag',
    'otimização de games competitivos',
    'setup para games',
    'performance em jogos online',
    'otimizador de hardware para games',
    'melhorar ping em jogos',
    'reduzir latência em games',
    'voltris optimizer',
    'software otimização pc',
    'acelerar computador',
    'programa para melhorar desempenho',
    'otimização windows 10',
    'otimização windows 11',
    'fps boost',
    'game performance',
    'otimização para cs2',
    'otimização para valorant',
    'otimização para league of legends',
    'otimização para fortnite',
    'software brasileiro',
    'tecnologia nacional',
    'saas otimização',
    'controle remoto otimização',
    'gestão de desempenho pc',
    'otimização corporativa',
    'produtividade windows',
    'manutenção preventiva ti',
    'solução ti empresarial'
  ],
  authors: [{ name: "VOLTRIS" }],
  creator: "VOLTRIS",
  publisher: "VOLTRIS",
  metadataBase: new URL('https://voltris.com.br'),
  alternates: {
    canonical: '/voltrisoptimizer',
  },
  openGraph: {
    type: 'website',
    locale: 'pt_BR',
    url: 'https://voltris.com.br/voltrisoptimizer',
    siteName: 'VOLTRIS',
    title: '[2025] VOLTRIS OPTIMIZER - Otimizador de PC Profissional | Aumente FPS, Desempenho e Produtividade',
    description: 'VOLTRIS OPTIMIZER: Software brasileiro de otimização de PC. Aumente até 25% de FPS, elimine stutter e lag, otimização automática para 100+ jogos, redução de input lag em até 40%. Solução SaaS com controle remoto para gamers, empresas e uso doméstico.',
    images: [
      {
        url: '/optimizer-banner.jpg',
        width: 1200,
        height: 630,
        alt: 'VOLTRIS Optimizer - Otimizador de PC Profissional para Gamers e Empresas',
      },
    ],
  },
  twitter: {
    card: 'summary_large_image',
    title: '[2025] VOLTRIS OPTIMIZER - Otimizador de PC Profissional | Aumente FPS, Desempenho e Produtividade',
    description: 'VOLTRIS OPTIMIZER: Software brasileiro de otimização de PC. Aumente até 25% de FPS, elimine stutter e lag, otimização automática para 100+ jogos, redução de input lag em até 40%. Solução SaaS com controle remoto.',
    images: ['/optimizer-banner.jpg'],
    creator: '@voltris',
  },
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },
};